Use OnlineStore;

CREATE TABLE [User] (
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL, 
[FirstName] VARCHAR(50) NULL,
[MiddleName] VARCHAR(50) NULL,
[LastName] VARCHAR(50) NULL,
[Username] VARCHAR(50) NULL,
[Password] VARCHAR(150) NULL,
[EmailAddress] VARCHAR(100) NULL,
[MobileNumber] VARCHAR (15) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [UserAddress](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id) NOT NULL,
[FirstLine] VARCHAR(500) NULL,
[SecondLine] VARCHAR(500) NULL,
[ThirdLine] VARCHAR(500) NULL,
[Postcode] VARCHAR(10) NULL,
[City] VARCHAR(100) NULL,
[County] VARCHAR(100) NULL,
[Country] VARCHAR(100) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [UserCreditType_Lookup]( --e.g. GestureOfGoodwill, RefundCredit, LoyaltyCredit
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NULL,
[Description] VARCHAR(250) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [UserCredit](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id) NOT NULL,
[UserCreditTypeId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [UserCreditType_Lookup](Id) NOT NULL,
[Value] DECIMAL (18, 2) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [Discount_Lookup]( --e.g. 3For1, Buy1Get1Free, PercentOff, SeasonalPercentOff
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NULL,
[Description] VARCHAR(250) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [ProductCategory_Lookup](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Name] VARCHAR (100) NULL,
[Description] VARCHAR(500) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [Product](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Category] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [ProductCategory_Lookup](Id) NOT NULL,
[Name] VARCHAR (100) NULL,
[Description] VARCHAR(500) NULL,
[Manufacturer] VARCHAR(50) NULL,
[Cost] DECIMAL NULL,
[SellingPrice] DECIMAL NULL,
[DiscountId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Discount_Lookup](Id) NULL,
[QuantityInStock] INT NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [Basket](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [User](Id) NOT NULL,
[DiscountId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Discount_Lookup](Id) NULL,
[BasketValue] DECIMAL (18, 2) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [BasketItem](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[BasketId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Basket](Id) NOT NULL,
[ProductId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Product](Id) NOT NULL,
[DiscountId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Discount_Lookup](Id) NULL,
[Quantity] INT DEFAULT 0 NULL,
[Price] DECIMAL (18, 2) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [PaymentType_Lookup]( --e.g. CreditCard, DebitCard, Credit, DirectDebit, DigitalWallet, BuyNowPayLater, 
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NULL,
[Description] VARCHAR(250) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [PaymentProvider_Lookup]( --e.g. WorldPay, ApplePay, GooglePay, SamsungPay, PayPal, Klarna, Stripe
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Name] VARCHAR(50) NULL,
[Description] VARCHAR(250) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [Payment](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[BasketId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Basket](Id) NOT NULL,
[PaymentTypeId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Basket](Id) NOT NULL,
[PaymentProviderId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [Basket](Id) NOT NULL,
[PaymentProviderPaymentReference] VARCHAR(500) NOT NULL,
[PaymentValue] DECIMAL (18, 2) NOT NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

--Separate tables for each commonly used payment provider with further payment details e.g. cardnumber(masked), sortcode, expirydate, full name, address etc., 
--Not commonly used payment providers in one generic table?

CREATE TABLE [Order](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
);

CREATE TABLE [OrderItem](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
);

CREATE TABLE [Shipping](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
);