Use OnlineStore;

CREATE TABLE [User] (
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL, 
[FirstName] VARCHAR(50) NULL,
[MiddleName] VARCHAR(50) NULL,
[LastName] VARCHAR(50) NULL,
[Username] VARCHAR(50) NULL,
[Password] VARCHAR(150) NULL,
[EmailAddress] VARCHAR(100) NULL,
[MobileNumber] VARCHAR (15) NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [Product](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
[Name] VARCHAR (100) NULL,
[Description] VARCHAR(500) NULL,
[Manufacturer] VARCHAR(50) NULL,
[Cost] DECIMAL NULL,
[SellingPrice] DECIMAL NULL,
[Discount] INT NULL,
[QuantityInStock] INT NULL,
[CreatedDate] DATETIME NULL,
[CreatedBy] UNIQUEIDENTIFIER NULL,
[ModifiedDate] DATETIME NULL,
[ModifiedBy] UNIQUEIDENTIFIER NULL
);

CREATE TABLE [Basket](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
);

CREATE TABLE [Order](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
);

CREATE TABLE [OrderItem](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
);

CREATE TABLE [Payment](
[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
);

